/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ep;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SMART
 */
public class Emp_pre extends javax.swing.JFrame {

    /**
     * Creates new form Emp_pre
     */
    public Emp_pre() {
        initComponents();
        fillcombo();
        fillcombo1();
        fillcombo2();
        fillcombo3();
        fillcombo4();
        fillcombo5();
    }
    
    private void fillcombo(){
    try{
          java.sql.Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/lnct","root","Anshu1697");
                    
          String sql="select * from leader";
          PreparedStatement ps=conn.prepareStatement(sql);
          ResultSet rst=ps.executeQuery();
          
          while(rst.next()){
          String name=rst.getString("Lead_id");
          ComboBox1.addItem(name);
          }
          
          ps.close();
          conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

}
    private void fillcombo1(){
    try{
          java.sql.Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/lnct","root","Anshu1697");
                    
          String sql="select * from emp";
          PreparedStatement ps=conn.prepareStatement(sql);
          ResultSet rst=ps.executeQuery();
          
          while(rst.next()){
          String name=rst.getString("Emp_id");
          ComboBox2.addItem(name);
          }
          
          ps.close();
          conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    

}
    private void fillcombo2(){
    try{
          java.sql.Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/lnct","root","Anshu1697");
                    
          String sql="select * from leader";
          PreparedStatement ps=conn.prepareStatement(sql);
          ResultSet rst=ps.executeQuery();
          
          while(rst.next()){
          String name=rst.getString("Lead_id");
          ComboBox3.addItem(name);
          }
          
          ps.close();
          conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

}
    private void fillcombo3(){
    try{
          java.sql.Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/lnct","root","Anshu1697");
                    
          String sql="select * from leader";
          PreparedStatement ps=conn.prepareStatement(sql);
          ResultSet rst=ps.executeQuery();
          
          while(rst.next()){
          String name=rst.getString("Lead_id");
          ComboBox4.addItem(name);
          }
          
          ps.close();
          conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

}
    private void fillcombo4(){
    try{
          java.sql.Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/lnct","root","Anshu1697");
                    
          String sql="select * from leader";
          PreparedStatement ps=conn.prepareStatement(sql);
          ResultSet rst=ps.executeQuery();
          
          while(rst.next()){
          String name=rst.getString("Lead_id");
          ComboBox5.addItem(name);
          }
          
          ps.close();
          conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

}
    private void fillcombo5(){
    try{
          java.sql.Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/lnct","root","Anshu1697");
                    
          String sql="select * from leader";
          PreparedStatement ps=conn.prepareStatement(sql);
          ResultSet rst=ps.executeQuery();
          
          while(rst.next()){
          String name=rst.getString("Lead_id");
          ComboBox6.addItem(name);
          }
          
          ps.close();
          conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        ComboBox6 = new javax.swing.JComboBox<>();
        ComboBox5 = new javax.swing.JComboBox<>();
        ComboBox4 = new javax.swing.JComboBox<>();
        ComboBox3 = new javax.swing.JComboBox<>();
        ComboBox1 = new javax.swing.JComboBox<>();
        ComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextField1.setText("Emp Id");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(192, 132, 88, 31);

        jTextField2.setText("Preference 1");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(192, 189, 88, 35);

        jTextField3.setText("Preference 2");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(192, 248, 88, 35);

        jTextField4.setText("Preference 3");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(192, 305, 88, 35);

        jTextField5.setText("Preference 4");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(192, 370, 88, 35);

        jTextField6.setText("Preference 5");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(192, 428, 88, 35);

        ComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBox6);
        ComboBox6.setBounds(640, 430, 103, 31);

        ComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBox5);
        ComboBox5.setBounds(640, 372, 103, 31);

        ComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBox4);
        ComboBox4.setBounds(640, 307, 103, 31);

        ComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBox3);
        ComboBox3.setBounds(640, 250, 103, 31);

        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBox1);
        ComboBox1.setBounds(640, 191, 103, 31);

        ComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBox2);
        ComboBox2.setBounds(640, 132, 103, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("                                       Employee Preference Order");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 11, 911, 63);

        Button.setText("Submit");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Button);
        Button.setBounds(410, 550, 98, 32);

        jButton2.setText("Output Frame");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(390, 600, 130, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ep/images/IMG-20190302-WA0007.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 80, 830, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void ComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox6ActionPerformed

    private void ComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox5ActionPerformed

    private void ComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox4ActionPerformed

    private void ComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox3ActionPerformed

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox1ActionPerformed

    private void ComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/lnct","root","Anshu1697");
            PreparedStatement ps;
            String sql ="Insert into emp_pre (E_id,E1,E2,E3,E4,E5) values (?,?,?,?,?,?)";
            ps=conn.prepareStatement(sql);
            String p=ComboBox2.getSelectedItem().toString();
            String v=ComboBox1.getSelectedItem().toString();
            String v1=ComboBox3.getSelectedItem().toString();
            String v2=ComboBox4.getSelectedItem().toString();
            String v3=ComboBox5.getSelectedItem().toString();
            String v4=ComboBox6.getSelectedItem().toString();
            System.out.println("haha yahan");
            ps.setString(1,p);
            ps.setString(2,v);
            ps.setString(3,v1);
            ps.setString(4,v2);
            ps.setString(5,v3);
            ps.setString(6,v4);
            int ans=ps.executeUpdate();
            System.out.println(ans);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Leader_Pre.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MainFrame m = new MainFrame();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_pre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_pre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_pre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_pre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_pre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox2;
    private javax.swing.JComboBox<String> ComboBox3;
    private javax.swing.JComboBox<String> ComboBox4;
    private javax.swing.JComboBox<String> ComboBox5;
    private javax.swing.JComboBox<String> ComboBox6;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
